name: Pages
on:
  push:
    branches:
    - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        architecture: "x64"
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: install theme
      run: |
            python.exe -m pip install --upgrade pip
            pip3 install sphinx-rtd-theme
            pip3 install .
    - name: Build and Commit
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: doc
    - name: Push changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        new_branch: gh-pages
        push: true
