name: Pages
on:
  push:
    branches:
    - dev
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Build and Commit
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: docs