name: Python FAIR Data Pipeline
on: [push]
jobs:
  test:
    name: Test ${{ matrix.os }} (Python ${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest,ubuntu-20.04,macos-latest]
        python: ["3.7"] #,"3.8", "3.9"]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: "x64"
      - name: Install graphviz
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install graphviz
          elif [ "$RUNNER_OS" == "Windows" ]; then
              choco install graphviz
          elif [ "$RUNNER_OS" == "Darwin" ]; then
              brew install graphviz
          fi
        shell: bash
      - name: Install local registry
        run: |
          if [ "$RUNNER_OS" != "Windows" ]; then
              curl -fsSL https://data.scrc.uk/static/localregistry.sh | /bin/bash -s -- -b main
          fi
        shell: bash
      - name: Checkout data-registry
        if: matrix.os == 'windows-latest'
        uses: actions/checkout@v2
        with:
          repository: FAIRDataPipeline/data-registry
          path: data-registry
      - name: Move registry
        if: matrix.os == 'windows-latest'
        run: |
              mkdir $HOME\.fair\registry
              Move-Item -Path "data-registry\*" -Destination "$HOME/.fair/registry"
      - name: install local registry on windows
        if: matrix.os == 'windows-latest'
        run: |
          python3 -m venv $HOME\.fair\registry\venv
          python -m pip install --upgrade pip wheel
          python -m pip install -r $HOME\.fair\registry\local-requirements.txt
          $env:DJANGO_SETTINGS_MODULE="drams.local-settings"
          $env:DJANGO_SUPERUSER_USERNAME="admin"
          $env:DJANGO_SUPERUSER_PASSWORD="admin"
          cd $HOME\.fair\registry
          python3 manage.py makemigrations custom_user
          python3 manage.py makemigrations data_management
          python3 manage.py migrate
          python3 manage.py collectstatic --noinput 
          python3 manage.py createsuperuser --noinput
      - name: Install Required
        run: brew install memcached
        if: matrix.os == 'macos-latest'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Checkout pySimpleModel
        uses: actions/checkout@v2
        with:
          repository: FAIRDataPipeline/pySimpleModel
          path: pySimpleModel
      - name: Move pySimpleModel
        run: mv pySimpleModel ../pySimpleModel
      - name: Run Tests on Windows
        run: |
          poetry install
          poetry shell
          pip install fair-cli
          pip install ../pySimpleModel
          fair init --ci
          fair registry start
          fair pull data_pipeline_api/ext/SEIRSconfig.yaml
          fair run data_pipeline_api/ext/SEIRSconfig.yaml

          python3 -m poetry run pytest --cov=data_pipeline_api  --cov-report=xml --cov-report=term -s tests/
        if: matrix.os == 'windows-latest'
      - name: Run Tests on other OS
        run: |
          poetry install
          source .venv/bin/activate
          pip install fair-cli
          pip install ../pySimpleModel
          fair init --ci
          fair registry start
          fair pull data_pipeline_api/ext/SEIRSconfig.yaml
          fair run data_pipeline_api/ext/SEIRSconfig.yaml

          python3 -m poetry run pytest --cov=data_pipeline_api  --cov-report=xml --cov-report=term -s tests/
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false
          verbose: true
        if: matrix.python == '3.9' && matrix.os == 'ubuntu-20.04'
