name: Python FAIR Data Pipeline
on: [push]
jobs:
  test:
    name: Test ${{ matrix.os }} (Python ${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest] #, windows-latest]
        python: ["3.7","3.8", "3.9"]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: "x64"
      - name: Install graphviz
        run:  |
              if [ ${{ runner.os }} == "Linux" ]; then
                  sudo apt-get install graphviz
              else
                  brew install graphviz
              fi
      - name: Install local registry
        run: curl -fsSL https://data.scrc.uk/static/localregistry.sh | /bin/bash -s -- -b main
      - name: Install Required
        run: brew install memcached
        if: matrix.os == 'macos-latest'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Run Tests
        run: |
          poetry install
          source .venv/bin/activate
          pip install fair-cli
          fair init --ci
          fair registry start
          fair pull simpleModel/ext/SEIRSconfig.yaml
          fair run simpleModel/ext/SEIRSconfig.yaml

          python3 -m poetry run pytest --cov=fairdatapipeline  --cov-report=xml --cov-report=term -s tests/
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false
          verbose: true
        if: matrix.python == '3.9' && matrix.os == 'ubuntu-20.04'
