name: Test
on: 
  push:
    branches:
      '**'
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1" # Run Every Monday at 9AM

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-emergency-bypass
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    name: testing
    steps:
      - uses: actions/checkout@v4
      - name: do something
        run: |
          echo "Ran Succesfully"
